// This file is auto-generated by scripts/set-env.js uesd in the build process. Do not edit this file directly.
export const environment = {
  production: true,
  backendUrl: 'https://pay.poupiempire.tech/',
  // backendUrl: 'http://localhost:3000/',

};

